/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DownloadRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'projectId' : IDL.Text,
  'timestamp' : IDL.Int,
  'format' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Features = IDL.Record({
  'fileUpload' : IDL.Bool,
  'pullToRefresh' : IDL.Bool,
  'pushNotifications' : IDL.Bool,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'outputFormat' : IDL.Text,
  'packageName' : IDL.Text,
  'features' : Features,
  'websiteUrl' : IDL.Text,
  'appName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'minSdk' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'splashColor' : IDL.Text,
  'iconKey' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDownloadRecord' : IDL.Func([IDL.Text, IDL.Text], [DownloadRecord], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Features,
        IDL.Opt(IDL.Text),
      ],
      [Project],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getProjectIcon' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyDownloadHistory' : IDL.Func([], [IDL.Vec(DownloadRecord)], ['query']),
  'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'updateProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Features,
        IDL.Opt(IDL.Text),
      ],
      [Project],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DownloadRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'projectId' : IDL.Text,
    'timestamp' : IDL.Int,
    'format' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Features = IDL.Record({
    'fileUpload' : IDL.Bool,
    'pullToRefresh' : IDL.Bool,
    'pushNotifications' : IDL.Bool,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'outputFormat' : IDL.Text,
    'packageName' : IDL.Text,
    'features' : Features,
    'websiteUrl' : IDL.Text,
    'appName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'minSdk' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'splashColor' : IDL.Text,
    'iconKey' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDownloadRecord' : IDL.Func([IDL.Text, IDL.Text], [DownloadRecord], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Features,
          IDL.Opt(IDL.Text),
        ],
        [Project],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getProjectIcon' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyDownloadHistory' : IDL.Func(
        [],
        [IDL.Vec(DownloadRecord)],
        ['query'],
      ),
    'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'updateProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Features,
          IDL.Opt(IDL.Text),
        ],
        [Project],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };