/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DownloadRecord {
  'id' : string,
  'userId' : Principal,
  'projectId' : string,
  'timestamp' : bigint,
  'format' : string,
}
export type ExternalBlob = Uint8Array;
export interface Features {
  'fileUpload' : boolean,
  'pullToRefresh' : boolean,
  'pushNotifications' : boolean,
}
export interface Project {
  'id' : string,
  'outputFormat' : string,
  'packageName' : string,
  'features' : Features,
  'websiteUrl' : string,
  'appName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'minSdk' : bigint,
  'updatedAt' : bigint,
  'splashColor' : string,
  'iconKey' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDownloadRecord' : ActorMethod<[string, string], DownloadRecord>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, string, string, string, bigint, Features, [] | [string]],
    Project
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], Project>,
  'getProjectIcon' : ActorMethod<[string], ExternalBlob>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyDownloadHistory' : ActorMethod<[], Array<DownloadRecord>>,
  'listMyProjects' : ActorMethod<[], Array<Project>>,
  'updateProject' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      Features,
      [] | [string],
    ],
    Project
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];